version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "install deps"
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment packages..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating lambda FN"
      - aws lambda update-function-code --function-name demo-github-to-lambda --zip-file fileb://deployment_package.zip
      - echo "=== DONE ==="
